export declare const devicesBreakpoints: {
    xl: string;
    l: string;
    Ipad: string;
    desktop: string;
    portable: string;
    midDevices: string;
    tablet: string;
    lapAndUp: string;
    pocket: string;
    handheldAndUp: string;
    thumb: string;
    medium: string;
    mediumUp: string;
    mediumDown: string;
    mobile: string;
    small: string;
    xSmall: string;
};
declare const breakpoints: {
    zero: number;
    xs: string;
    sm: string;
    md: string;
    lg: string;
    xl: string;
    xxl: string;
    xxxl: string;
    xxxxl: string;
};
export default breakpoints;
